api_version = "2026-07"

[[extensions]]
name = "receipt-recipient"
handle = "receipt-recipient"
uid = "5d106a25-b178-b4f4-30d0-cb676b6b6d1608fa9c0c"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/Checkout.tsx"
  # Plus 不要な動的ブロック。マーチャントがチェックアウトエディタで任意の位置に配置可能。
  target = "purchase.checkout.block.render"

  [extensions.capabilities]
  network_access = false
  block_progress = false
  api_access = false
