# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af48658e423b34562bde29eec7de36ab"
name = "ryousyusyo"
application_url = "https://shopify-receipt-app.onrender.com"
embedded = true

[build]
# 本番 URL を固定したいので dev 時の自動上書きはオフ
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,write_files"

[auth]
redirect_urls = [
  "https://shopify-receipt-app.onrender.com/api/auth",
  "https://shopify-receipt-app.onrender.com/auth/callback",
  "https://shopify-receipt-app.onrender.com/auth/shopify/callback",
]
